[package]
name = "vite-plugin-macro"
version = "0.1.0"
authors = ["Manu MA <manu.mtza@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }
swc_ecmascript = { version = "0.230.21", features = [ "utils", "visit", "parser", "transforms"] }
swc_common = { version = "0.31.16", features = ["sourcemap"] }
swc_atoms = "0.5.6"
anyhow = "1.0.70"
serde = { version = "1.0.160", features = ["derive"] }
serde_bytes = "0.11.9"
serde_json = "1.0.96"
simple-error = "0.3.0"
serde-wasm-bindgen = "0.4"
js-sys = "0.3.64"


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }
getrandom = { version = "0.2.10", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true

